import { ArgKind } from './model';

export interface Preset {
    text: string;
    kind: ArgKind;
    category: string;
    description: string;
    // Usability requirements, surfaced as hints in the catalog:
    details?: string;          // expanded notes shown when the row is unfolded
    bin?: string;              // wrapper binary that must exist on the system
    proton?: boolean;          // only meaningful for games run through Proton
    gpu?: 'nvidia' | 'amd' | 'mesa';  // vendor-specific (mesa = any Mesa-driven GPU)
}

// Built-in catalog of commonly used launch options on Linux/Proton.
// kind 'env' items go before %command%, 'wrapper' items wrap the command,
// 'flag' items are appended to the game's own command line.
export const PRESETS: Preset[] = [
    // ── Wrappers ────────────────────────────────────────────────────────────
    { kind: 'wrapper', category: 'Wrappers', text: 'gamemoderun', description: 'Feral GameMode: CPU governor → performance, priority tweaks while the game runs', bin: 'gamemoderun' , details: 'Requests the GameMode daemon to apply optimizations while the game runs: CPU governor to performance, process niceness/ioprio, optional GPU performance mode, and screensaver inhibition. Config via /etc/gamemode.ini or ~/.config/gamemode.ini. Redundant if you already use game-performance (pick one).' },
    { kind: 'wrapper', category: 'Wrappers', text: 'game-performance', description: 'CachyOS: switch power profile to performance while the game runs', bin: 'game-performance' , details: 'CachyOS helper that switches the power-profiles-daemon profile to \'performance\' for the lifetime of the game, restoring the previous profile on exit. Lighter alternative to GameMode on CachyOS; combining both is redundant.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'mangohud', description: 'MangoHud FPS/frametime/temps overlay (Vulkan; do not use under gamescope — use --mangoapp there)', bin: 'mangohud' , details: 'Vulkan/OpenGL overlay showing FPS, frametimes, CPU/GPU load and temperatures. Configure via ~/.config/MangoHud/MangoHud.conf or the MANGOHUD_CONFIG env var. Toggle with Shift_R+F12 by default. Under gamescope use \'gamescope --mangoapp\' instead of this wrapper.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'mangohud --dlsym', description: 'MangoHud for OpenGL games that misbehave with default hooking', bin: 'mangohud' , details: 'Same as mangohud, but uses dlsym-based hooking for OpenGL games where the default hook fails to draw the overlay (some native GL titles and older engines).' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -f --', description: 'Gamescope micro-compositor, fullscreen (the -- must stay last)', bin: 'gamescope' , details: 'Runs the game inside Valve\'s gamescope micro-compositor in fullscreen. Isolates the game from your desktop compositor: fixes alt-tab glitches, forces correct resolution/scaling, enables clean FSR upscaling and VRR control. Everything before \'--\' configures gamescope; the game command follows it.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -W 2560 -H 1440 -f --', description: 'Gamescope at a fixed output resolution (edit -W/-H)', bin: 'gamescope' , details: 'Gamescope with an explicit output size (-W/-H = what your monitor receives). The game renders at the same size unless you add -w/-h for a lower internal resolution.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -w 1280 -h 720 -W 1920 -H 1080 -F fsr --', description: 'Gamescope: render low (-w/-h), FSR-upscale to output (-W/-H); --fsr-sharpness 0-20', bin: 'gamescope' , details: 'Renders the game at 1280x720 (-w/-h) and upscales to 1920x1080 (-W/-H) with FSR1 (-F fsr). Add --fsr-sharpness 0-20 to tune (lower = sharper). Big FPS win on weak GPUs at the cost of some clarity; \'nis\' is an alternative scaler.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -f --mangoapp --', description: 'Gamescope with MangoHud inside (plain mangohud is unsupported under gamescope)', bin: 'gamescope' , details: 'Gamescope fullscreen with the MangoHud overlay rendered by gamescope itself (--mangoapp). This is the only supported way to get MangoHud inside gamescope — the plain mangohud wrapper conflicts with it.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -f -r 144 --adaptive-sync --', description: 'Gamescope fullscreen with refresh-rate hint + VRR', bin: 'gamescope' , details: 'Gamescope fullscreen advertising a 144 Hz refresh target and enabling adaptive sync (VRR/FreeSync/G-Sync) inside the gamescope session. Match -r to your monitor\'s refresh rate.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope -f --hdr-enabled --', description: 'HDR passthrough via gamescope (Wayland + supporting GPU)', bin: 'gamescope' , details: 'Enables HDR passthrough inside gamescope. Needs a Wayland session, an HDR-capable monitor and driver stack (RDNA2+/recent Mesa work best). Independent from Proton\'s Wine-Wayland HDR path — don\'t combine both blindly.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'gamescope --force-grab-cursor --', description: 'Fix mouse escaping the window / wrong sensitivity', bin: 'gamescope' , details: 'Forces gamescope to confine the cursor to the game window. Fixes games where the mouse escapes to another monitor or has wrong sensitivity due to broken relative-mouse handling.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'prime-run', description: 'NVIDIA PRIME render offload (hybrid-GPU laptops)', bin: 'prime-run' , details: 'NVIDIA render-offload wrapper from Arch\'s nvidia-prime package: expands to __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia, making this one game render on the dGPU while the desktop stays on the iGPU. Only relevant on hybrid (Optimus) laptops.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'obs-gamecapture', description: 'Hook game for OBS vkcapture (capture without window grab)', bin: 'obs-gamecapture' , details: 'Preloads the obs-vkcapture layer so OBS\'s \'Game Capture\' source can grab the game\'s frames directly from Vulkan/OpenGL — far cheaper than window/screen capture and works under gamescope too. Requires obs-vkcapture installed.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'strangle 60', description: 'libstrangle FPS cap (edit the number; OpenGL/Vulkan)', bin: 'strangle' , details: 'libstrangle FPS limiter for OpenGL/Vulkan. The number is the cap; \'strangle 60:30\' sets separate focused/unfocused caps. Lighter than driver-level caps; alternative to MangoHud\'s fps_limit or DXVK_FRAME_RATE.' },
    { kind: 'wrapper', category: 'Wrappers', text: 'taskset -c 0-7', description: 'Pin the game to specific CPU cores (P/E-core or CCD tuning)', bin: 'taskset' , details: 'Pins the game to a fixed CPU core set (here cores 0-7). Useful to keep games off E-cores on Intel hybrid CPUs or on one CCD on dual-CCD Ryzens (e.g. the X3D cache die). Adjust the core list to your topology — check with lscpu.' },

    // ── Proton behavior ─────────────────────────────────────────────────────
    { kind: 'env', category: 'Proton', text: 'PROTON_LOG=1', description: 'Write Proton debug log to ~/steam-<appid>.log', proton: true , details: 'Writes a verbose Proton/Wine log to ~/steam-<appid>.log (override dir with PROTON_LOG_DIR). First thing to enable when a game crashes or fails to start; the log shows missing DLLs, Vulkan errors and Wine crashes. Remove it afterwards — logging costs performance.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_ENABLE_WAYLAND=1', description: 'Native Wayland Wine driver — better latency; experimental, breaks Steam Overlay/Input', proton: true , details: 'Runs Wine\'s native Wayland driver instead of XWayland (Proton 9+/GE). Lower latency, better fractional scaling and proper VRR, but experimental: Steam Overlay and Steam Input often break, and some games render black. Pair with PROTON_ENABLE_HDR=1 for HDR.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_ENABLE_HDR=1', description: 'HDR via Wine-Wayland (requires PROTON_ENABLE_WAYLAND=1 too)', proton: true , details: 'Enables HDR through Wine\'s Wayland backend. Requires PROTON_ENABLE_WAYLAND=1, a Wayland session with HDR enabled, and a recent GE-Proton. The gamescope --hdr-enabled route is the alternative; use one or the other.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_NO_ESYNC=1', description: 'Disable esync — try if a game crashes or behaves oddly', proton: true , details: 'Disables eventfd-based synchronization. Some games (often older or anti-cheat-protected ones) deadlock or behave oddly with esync; this trades a little performance for stability. Try together with PROTON_NO_FSYNC=1.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_NO_FSYNC=1', description: 'Disable fsync (falls back to esync)', proton: true , details: 'Disables futex-based fsync, falling back to esync. Use when a game stutters or crashes in ways that look synchronization-related; combine with PROTON_NO_ESYNC=1 to get plain wineserver sync.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_USE_NTSYNC=1', description: 'Kernel NTSYNC sync primitives (kernel 6.14+, GE-Proton 10-9+)', proton: true , details: 'Uses the kernel\'s NTSYNC driver (/dev/ntsync, kernel 6.14+) for Windows synchronization primitives — more correct than esync/fsync and fixes some stubborn games. Supported by GE-Proton 10-9+ and recent CachyOS kernels.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_USE_WOW64=1', description: 'New WoW64 mode for 32-bit games (pairs well with ntsync)', proton: true , details: 'Runs 32-bit Windows games through Wine\'s new WoW64 layer (32-on-64) instead of a full 32-bit prefix. Enables ntsync for 32-bit titles and avoids 32-bit library issues; experimental — test per game.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_USE_WINED3D=1', description: 'OpenGL wined3d instead of DXVK (old GPUs without Vulkan)', proton: true , details: 'Translates D3D9/10/11 to OpenGL via wined3d instead of Vulkan via DXVK. Almost always slower — only for GPUs without Vulkan support or to work around a specific DXVK bug.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_FSR4_UPGRADE=1', description: 'GE-Proton: swap FSR2/3 DLLs to FSR4 (RDNA3/4)', proton: true , details: 'GE-Proton: redirects the game\'s FSR2/3 DLLs to FSR4. Needs an RDNA3/RDNA4 GPU and a game shipping upgradable FSR DLLs. Check ProtonDB reports for per-game success.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_DLSS_UPGRADE=1', description: 'GE-Proton: upgrade DLSS DLLs to latest', proton: true , details: 'GE-Proton: swaps the game\'s bundled DLSS DLLs for the newest version (incl. preset overrides). NVIDIA RTX only; harmless if the game has no DLSS.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_HIDE_NVIDIA_GPU=1', description: 'Report NVIDIA GPU as AMD (games that block NV features under Wine)', proton: true , details: 'Makes Wine report an AMD GPU to the game. Workaround for titles that enable broken NVIDIA-specific paths (or refuse to run GeForce features) under Proton.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_FORCE_LARGE_ADDRESS_AWARE=1', description: 'Let 32-bit games use more than 2 GB RAM', proton: true , details: 'Lets 32-bit games address up to 4 GB instead of 2 GB. Fixes out-of-memory crashes in heavily modded oldies (Skyrim LE-era, GTA:SA with mods, etc.). No effect on 64-bit games.' },
    { kind: 'env', category: 'Proton', text: 'PROTON_SET_GAME_DRIVE=1', description: 'Create an S: drive pointing at the game’s Steam library', proton: true , details: 'Adds an S: drive inside the prefix pointing at the game\'s Steam library folder. Helps mod managers and games with hardcoded paths see the install location.' },
    { kind: 'env', category: 'Proton', text: 'STEAM_COMPAT_DATA_PATH=/path/to/prefix', description: 'Custom Proton prefix location (edit the path; saves live inside it)', proton: true , details: 'Relocates the Proton prefix (the per-game Windows environment, normally steamapps/compatdata/<appid>). Lets several games share one prefix or moves saves/prefix to another drive. The path must exist; remember saves often live inside the prefix.' },
    { kind: 'env', category: 'Proton', text: 'STEAM_COMPAT_MOUNTS=/path1:/path2', description: 'Bind extra host paths into the pressure-vessel container (mods on other drives)', proton: true , details: 'Makes extra host directories visible inside Proton\'s pressure-vessel container (colon-separated). Needed when mods, custom soundtracks or tools live on another drive that the game can\'t see.' },
    { kind: 'env', category: 'Proton', text: 'WINEDLLOVERRIDES=dinput8=n,b', description: 'DLL override (native,builtin) — needed by many mod loaders (edit DLL name)', proton: true , details: 'Forces Wine to load a native (n) DLL from the game folder before its builtin (b). dinput8 is the classic hook for mod loaders (ScriptHook, ASI loaders, BepInEx variants); replace with the DLL your mod framework needs, e.g. winhttp=n,b or version=n,b.' },
    { kind: 'env', category: 'Proton', text: 'WINEDEBUG=-all', description: 'Silence Wine debug output', proton: true , details: 'Silences all Wine debug channels. Tiny CPU saving in debug-spammy games; mostly useful to keep logs clean. The opposite of PROTON_LOG=1 — don\'t combine.' },
    { kind: 'env', category: 'Proton', text: 'WINE_FULLSCREEN_INTEGER_SCALING=1', description: 'Sharp integer scaling when upscaling', proton: true , details: 'Integer (pixel-perfect) scaling for fullscreen games at low resolutions — crisp pixels instead of blur for retro/pixel-art titles on high-DPI displays.' },
    { kind: 'env', category: 'Proton', text: 'LANG=ja_JP.UTF-8', description: 'Force locale — region-locked content / mojibake fixes (edit locale)' , details: 'Sets the locale the game sees. Unlocks region-locked content in some Japanese titles and fixes mojibake (garbled text) in games that assume a specific codepage. Use any locale you have generated on the system.' },
    { kind: 'env', category: 'Proton', text: 'PULSE_LATENCY_MSEC=60', description: 'Fix crackling audio in Wine/Proton games' , details: 'Increases PulseAudio/PipeWire-pulse buffer latency for the game. The classic fix for crackling or popping audio in Wine titles; try 60-90. Native games rarely need it.' },
    { kind: 'env', category: 'Proton', text: 'LD_PRELOAD=', description: 'Strip Steam overlay preload — fixes crashes/stutter in some titles (disables overlay)' , details: 'Clears LD_PRELOAD for the game, dropping Steam\'s overlay/gameoverlayrenderer hooks. Fixes startup crashes and stutter in sensitive titles, but the Steam Overlay (and its screenshot/FPS features) stops working for that game.' },

    // ── Graphics / DXVK / VKD3D / Mesa / NVIDIA ─────────────────────────────
    { kind: 'env', category: 'Graphics', text: 'DXVK_HUD=fps,frametimes', description: 'DXVK overlay with FPS + frametime graph (or DXVK_HUD=full)', proton: true , details: 'DXVK\'s built-in overlay for D3D9/10/11 games: fps + frametime graph. Other useful tokens: devinfo, gpuload, memory, compiler (shader compile activity), version; \'full\' shows everything. Lighter than MangoHud but DXVK-only.' },
    { kind: 'env', category: 'Graphics', text: 'DXVK_FRAME_RATE=60', description: 'DXVK-level FPS cap for D3D9/10/11 games (edit the number)', proton: true , details: 'Caps the frame rate inside DXVK (D3D9/10/11 under Proton). Works where in-game limiters are missing or broken; no tearing interaction with VRR. For Vulkan-native or D3D12 games use MangoHud\'s fps_limit or gamescope -r instead.' },
    { kind: 'env', category: 'Graphics', text: 'DXVK_ASYNC=1', description: 'Legacy: async shader compile — only dxvk-gplasync builds; no-op on modern DXVK', proton: true , details: 'Legacy switch for dxvk-async/gplasync forks: compiles pipelines asynchronously to avoid shader-compile stutter, at the cost of brief visual artifacts. Modern DXVK (2.x) ships graphics-pipeline-library support that makes this unnecessary — only keep it if you specifically run a gplasync build.' },
    { kind: 'env', category: 'Graphics', text: 'VKD3D_CONFIG=dxr', description: 'Enable DirectX Raytracing in vkd3d-proton', proton: true , details: 'Enables DirectX Raytracing translation in vkd3d-proton for D3D12 games. Needs a GPU + driver with VK_KHR_ray_tracing. Other tokens: dxr11, no_upload_hvv, force_static_cbv (comma-separated).' },
    { kind: 'env', category: 'Graphics', text: 'RADV_PERFTEST=gpl', description: 'RADV experimental features (value varies by Mesa version)', gpu: 'amd' , details: 'Opt-in flags for Mesa\'s RADV Vulkan driver. Available values change between Mesa releases (historically gpl, rt, sam, nggc...) — check the Mesa docs for your version; stale values are silently ignored.' },
    { kind: 'env', category: 'Graphics', text: 'AMD_VULKAN_ICD=RADV', description: 'Force RADV when AMDVLK/PRO is also installed', gpu: 'amd' , details: 'Picks the RADV (Mesa) Vulkan driver when AMDVLK or AMDGPU-PRO is also installed and would otherwise be chosen. RADV is what Valve targets and is almost always the right answer for gaming.' },
    { kind: 'env', category: 'Graphics', text: 'MESA_VK_WSI_PRESENT_MODE=immediate', description: 'Mesa Vulkan: no VSync (mailbox / fifo = vsync)', gpu: 'mesa' , details: 'Forces the Vulkan present mode for Mesa drivers: immediate = no vsync (tearing possible), mailbox = low-latency vsync, fifo = standard vsync, relaxed = adaptive. Affects RADV/ANV/etc., not NVIDIA.' },
    { kind: 'env', category: 'Graphics', text: 'mesa_glthread=true', description: 'Mesa OpenGL threaded dispatch (boosts some GL games)', gpu: 'mesa' , details: 'Enables Mesa\'s threaded OpenGL dispatch. Decent FPS gains in draw-call-heavy GL games (Minecraft, older ports); a few titles misbehave — easy to toggle per game here.' },
    { kind: 'env', category: 'Graphics', text: 'vblank_mode=0', description: 'Mesa OpenGL: disable VSync', gpu: 'mesa' , details: 'Disables vsync for Mesa OpenGL games (3 forces it on). OpenGL-only; for Vulkan use MESA_VK_WSI_PRESENT_MODE=immediate.' },
    { kind: 'env', category: 'Graphics', text: '__GL_THREADED_OPTIMIZATIONS=1', description: 'NVIDIA: threaded OpenGL optimizations', gpu: 'nvidia' , details: 'NVIDIA\'s threaded OpenGL optimizations. Helps some GL games (source ports, emulators); can cause stutter in others — test per title. Vulkan games ignore it.' },
    { kind: 'env', category: 'Graphics', text: '__GL_SYNC_TO_VBLANK=0', description: 'NVIDIA OpenGL: VSync off', gpu: 'nvidia' , details: 'Disables vsync in NVIDIA\'s OpenGL driver. OpenGL-only; Vulkan present mode is controlled by the game/layer instead.' },
    { kind: 'env', category: 'Graphics', text: '__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia', description: 'NVIDIA PRIME offload without the prime-run script', gpu: 'nvidia' , details: 'The raw env-var pair behind prime-run: renders this game on the NVIDIA dGPU in a hybrid-graphics laptop while the desktop stays on the integrated GPU. Add __VK_LAYER_NV_optimus=NVIDIA_only for some Vulkan titles.' },
    { kind: 'env', category: 'Graphics', text: 'DRI_PRIME=1', description: 'Mesa dGPU offload (AMD/Intel hybrid systems)' , details: 'Mesa\'s render-offload switch for hybrid AMD/Intel systems: runs the game on the discrete GPU. DRI_PRIME=pci-XXXX_YY_ZZ_W selects a specific card on multi-GPU setups (see DRI_PRIME in Mesa docs).' },
    { kind: 'env', category: 'Graphics', text: 'ENABLE_VKBASALT=1', description: 'vkBasalt post-processing (CAS sharpening, ReShade FX)', bin: 'vkBasalt' , details: 'Enables the vkBasalt Vulkan post-processing layer: CAS sharpening, FXAA/SMAA, LUTs and ReShade FX shaders. Configure effects in ~/.config/vkBasalt/vkBasalt.conf; toggle in-game with the Home key by default.' },
    { kind: 'env', category: 'Graphics', text: 'MANGOHUD=1', description: 'MangoHud via Vulkan layer env (alternative to the wrapper)', bin: 'mangohud' , details: 'Loads MangoHud via its Vulkan implicit layer instead of the wrapper command — useful where the wrapper is awkward (some launchers) or for native Vulkan games. OpenGL games still need the mangohud wrapper.' },
    { kind: 'env', category: 'Graphics', text: 'MANGOHUD_CONFIG=fps_limit=60', description: 'Inline MangoHud config (e.g. no_display, cpu_temp,gpu_temp)', bin: 'mangohud' , details: 'Inline MangoHud configuration without editing config files. Comma-separated options: fps_limit=60, no_display (limiter without overlay), cpu_temp,gpu_temp, frame_timing, position=top-right, etc.' },
    { kind: 'env', category: 'Graphics', text: 'SDL_VIDEODRIVER=wayland', description: 'Native Wayland for SDL games (x11 forces XWayland instead)' , details: 'Makes SDL2/SDL3 games use native Wayland instead of XWayland: sharper fractional scaling and lower latency. Some games break (cursor grabs, popups) — switch to x11 to force XWayland when that happens.' },

    // ── Common game flags ───────────────────────────────────────────────────
    { kind: 'flag', category: 'Game flags', text: '-novid', description: 'Skip intro videos (Source engine: CS2, TF2, …)' , details: 'Skips the intro/valve logo videos in Source-engine games (CS2, TF2, L4D2, Portal...). Saves a few seconds every launch.' },
    { kind: 'flag', category: 'Game flags', text: '-skipintro', description: 'Skip intro movies (many engines; name varies)' , details: 'Skips intro movies in many engines (varies by game — some use -SkipIntro, --skip-intro or ini edits; check PCGamingWiki for the exact spelling your game expects).' },
    { kind: 'flag', category: 'Game flags', text: '-nosplash', description: 'Disable splash screen (UE, Arma, others)' , details: 'Disables the splash/launcher screen in Unreal, Arma, DayZ and others, going straight to the game.' },
    { kind: 'flag', category: 'Game flags', text: '-nolauncher', description: 'Bypass the game’s own launcher where supported' , details: 'Bypasses the game\'s own pre-launcher where supported (several Paradox titles, some indies). If the game ignores it, the launcher usually has its own skip setting.' },
    { kind: 'flag', category: 'Game flags', text: '-fullscreen', description: 'Force fullscreen' , details: 'Forces exclusive fullscreen where the engine supports the flag (Source and many others).' },
    { kind: 'flag', category: 'Game flags', text: '-windowed -noborder', description: 'Borderless windowed' , details: 'Borderless windowed mode: the universal pair for Source games and many engines. Smooth alt-tab; combine with -w/-h to size the window.' },
    { kind: 'flag', category: 'Game flags', text: '-w 1920 -h 1080', description: 'Force resolution (edit values)' , details: 'Forces the render/window resolution. Useful when a game boots at a wrong resolution or for windowed setups; pairs with -windowed -noborder.' },
    { kind: 'flag', category: 'Game flags', text: '-vulkan', description: 'Use the Vulkan renderer where supported (CS2, BG3, …)' , details: 'Switches the game\'s renderer to Vulkan where supported (CS2, Dota 2, BG3, some id Tech and Unity titles). On Linux this often performs better than the DX-translated path.' },
    { kind: 'flag', category: 'Game flags', text: '-dx11', description: 'Force DirectX 11 (Unreal Engine and others)' , details: 'Forces the DirectX 11 renderer in Unreal Engine and other multi-renderer games (sometimes spelled -d3d11 or -force-d3d11 in Unity). Useful when the game\'s DX12 path stutters under vkd3d-proton.' },
    { kind: 'flag', category: 'Game flags', text: '-dx12', description: 'Force DirectX 12 (Unreal Engine and others)' , details: 'Forces DirectX 12 (UE: also -d3d12). Worth testing both ways under Proton — DX12 via vkd3d-proton sometimes beats DX11 via DXVK, sometimes not.' },
    { kind: 'flag', category: 'Game flags', text: '-nojoy', description: 'Disable joystick support — faster startup, fixes input bugs (Source)' , details: 'Disables joystick/gamepad initialization in Source games: faster startup and fixes phantom-input bugs when you play with mouse and keyboard.' },
    { kind: 'flag', category: 'Game flags', text: '-high', description: 'High CPU priority (Source)' , details: 'Asks the game to start at high CPU priority (Source). Largely superseded by GameMode\'s renicing; avoid combining both.' },
    { kind: 'flag', category: 'Game flags', text: '-useallavailablecores', description: 'Hint to use all CPU cores (UE3/4-era titles)' , details: 'Legacy hint telling UE3/UE4-era and some other engines to use all CPU cores. Many modern games ignore it; harmless either way.' },
    { kind: 'flag', category: 'Game flags', text: '-console', description: 'Enable developer console (Source)' , details: 'Enables the developer console in Source games (open with ~). Needed for many fixes and tweaks.' },
    { kind: 'flag', category: 'Game flags', text: '-language english', description: 'Force game language (Source; edit language)' , details: 'Forces the game language (Source and several other engines). The value is the English name of the language: english, german, russian, ...' },
    { kind: 'flag', category: 'Game flags', text: '-autoconfig', description: 'Reset video settings to defaults (Source recovery)' , details: 'Resets all video settings to engine defaults on launch (Source). Recovery flag for black screens or broken configs — remove it after one successful start.' },
    { kind: 'flag', category: 'Game flags', text: '-force-vulkan', description: 'Unity: force the Vulkan renderer' , details: 'Unity: forces the Vulkan renderer (-force-glcore for OpenGL core). Helps Unity titles that default to a broken renderer under Proton.' },
    { kind: 'flag', category: 'Game flags', text: '-screen-fullscreen 0 -popupwindow', description: 'Unity: windowed/borderless' , details: 'Unity: windowed (-screen-fullscreen 0) plus borderless (-popupwindow). The Unity equivalent of -windowed -noborder.' },
];

export const PRESET_CATEGORIES: string[] = [...new Set(PRESETS.map((p) => p.category))];
